### ISSUE TITLE
Disable automatic version check

### ISSUE THREAD

**Issue by MatteoJoliveau** [johndcarmichael/boats#21]
Hello! I'm using Boats to assemble and build the OpenAPI spec for an application I'm developing.

Boats gets invoked every time the application is compiled, which is done automatically in a CI pipeline and when building the Docker image. Every now and then the build is broken by the following message produced by Boats:

```
Checking version with npm-tool-version-check from: https://raw.githubusercontent.com/johndcarmichael/boats/master/package.json
WARNING: The version of BOATS you are running, 1.20.4, is OUTDATED!
THERE IS A BETTER VERSION: 1.23.0
? Are you sure you want to continue with an outdated package? This will result in some serious technical dept in the future and prevent security updates arriving... (y/N)
```

 Is there a way I can disable this check so that the build can proceed even if I'm using an older version of boats?
Upgrading a dependency is something that requires careful consideration and is always done manually to validate the new build, I cannot afford to have broken builds due to a tool that wants to update itself.

**Comment by p-mcgowan** [comment]
One workaround you can use is to set `NODE_ENV=test`, which skips the version check

**Comment by MatteoJoliveau** [comment]
@p-mcgowan I see the PR, I like the proposed `--yes` flag. I'll wait for the change to be released and use the `NODE_ENV` workaround in the meantime, thank you so much for the very quick response! Love the project btw

**Comment by p-mcgowan** [comment]
@MatteoJoliveau thanks! We like it too and we're happy to see it in the wild.

It's still in active development and use and we are always happy to receive community feedback so we can continue to make it better!
