### ISSUE TITLE
discriminator / mapping + $ref doesn't seem to work

### ISSUE THREAD

**Issue by TomFreeman** [johndcarmichael/boats#43]
For example, with a fragment of spec like so:

``` yaml
items:
  discriminator:
    mapping:
      First: Specfile_ThingOne.yaml
      Second: Specfile_ThingTwo.yaml
    propertyName: thingType
  oneOf:
  - $ref: Specfile_ThingOne.yaml
  - $ref: Specfile_ThingTwo.yaml
```

It generates a rendered file like so:

``` yaml
items:
  discriminator:
    mapping:
      First: Specfile_ThingOne.yaml
      Second: Specfile_ThingTwo.yaml
    propertyName: thingType
  oneOf:
  - $ref: '#/components/schemas/FolderNameSpecFileThingOneYaml'
  - $ref: '#/components/schemas/FolderNameSpecFileThingTwoYaml'
```

As the mappings on first/second aren't templated the same way, the rendered spec doesn't work.

Not sure if this is a problem in the nunjunks templating or `json-schema-ref-parser`, or both.

We could guess the generated name for the indexed file, but that seems error prone.

**Comment by johndcarmichael** [comment]
@TomFreeman  would you be able to provide a .zip or repo somewhere with the files so we can try to replicate the issue please?

**Comment by TomFreeman** [comment]
I'll try and craft a PR showing the issue, as trying to unpick the specific part from our repo will be onerous.

**Comment by johndcarmichael** [comment]
Sounds good - a PR to the sample files could also work

**Comment by johndcarmichael** [comment]
https://github.com/johndcarmichael/boats/blob/master/srcOA3/index.yml.njk
